# Generated by Django 6.1.1 on 2026-09-13 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('level', models.CharField(choices=[('A', 'Уровень A (Легкий)'), ('B', 'Уровень B (Средний)'), ('C', 'Уровень C (Сложный)')], max_length=1, verbose_name='Уровень')),
                ('description', models.TextField(verbose_name='Описание')),
                ('input_example', models.TextField(verbose_name='Пример ввода')),
                ('output_example', models.TextField(verbose_name='Пример вывода')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя и Фамилия')),
                ('school_class', models.CharField(max_length=10, verbose_name='Класс (например, 10А)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TODO', 'В Бэклоге'), ('IN_PROGRESS', 'В работе'), ('TESTING', 'На проверке'), ('DONE', 'Решено')], default='TODO', max_length=15)),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код ученика')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы (0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.task')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Входные данные')),
                ('expected_output', models.TextField(verbose_name='Ожидаемый вывод')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='contest.task')),
            ],
        ),
    ]
