# Generated by Django 6.1.1 on 2026-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_cases',
            field=models.JSONField(default=list, help_text="Список словарей [{'input': '...', 'output': '...'}]"),
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
