# Generated by Django 6.1.1 on 2026-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_task_test_cases_delete_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='Комментарий преподавателя', null=True),
        ),
    ]
