# Generated by Django 6.1.1 on 2026-09-16 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_teachers_group(apps, schema_editor):
    """Группа 'Teachers' с правами ровно на то, что нужно учителю:
    курсы и темы (создать курс), теги (добавить/изменить/удалить),
    и просмотр/изменение задач (чтобы можно было менять теги задачи).
    Права на модель Teacher сюда не входят — назначать учителей может только админ."""
    from django.apps import apps as global_apps
    from django.contrib.auth.management import create_permissions
    from django.contrib.auth.models import Group, Permission

    # Права для модели Teacher (только что созданной в этой миграции) и для
    # Course/Tag/Topic (из предыдущей миграции) гарантированно создаются
    # прямо сейчас, не дожидаясь сигнала post_migrate.
    create_permissions(global_apps.get_app_config('contest'), verbosity=0)

    codenames = [
        'add_course', 'change_course', 'delete_course', 'view_course',
        'add_topic', 'change_topic', 'delete_topic', 'view_topic',
        'add_tag', 'change_tag', 'delete_tag', 'view_tag',
        'view_task', 'change_task',
    ]
    perms = Permission.objects.filter(content_type__app_label='contest', codename__in=codenames)

    group, _ = Group.objects.get_or_create(name='Teachers')
    group.permissions.set(perms)


def remove_teachers_group(apps, schema_editor):
    from django.contrib.auth.models import Group
    Group.objects.filter(name='Teachers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0004_course_tag_task_tags_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_visible",
            field=models.BooleanField(
                default=False,
                help_text="Пока не включено — курс виден только учителям/админу",
                verbose_name="Видно ученикам",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Имя и Фамилия"),
                ),
                (
                    "classes",
                    models.CharField(
                        blank=True,
                        help_text="Классы этого учителя через запятую, например: 10А, 11Б",
                        max_length=255,
                        verbose_name="Классы",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="contest.course",
                        verbose_name="Курсы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to="contest.teacher",
                verbose_name="Кем создан",
            ),
        ),
        migrations.RunPython(create_teachers_group, remove_teachers_group),
    ]
