# Generated by Django 6.1.1 on 2026-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0005_course_is_visible_teacher_course_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="last_submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя отправка на проверку"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="test_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список словарей [{'input': '...', 'output': '...'}] — необязательно, можно добавить позже",
            ),
        ),
    ]
