# Generated by Django 6.1.1 on 2026-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0006_submission_last_submitted_at_alter_task_test_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="theory_video_url",
            field=models.URLField(
                blank=True,
                help_text="Необязательно. Ученик увидит видео в начале темы.",
                verbose_name="Ссылка на теорию (YouTube)",
            ),
        ),
    ]
