# Generated by Django 6.1.1 on 2026-09-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0007_topic_theory_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="theory_video_url",
            field=models.URLField(
                blank=True,
                help_text="Необязательно. Ученик сможет открыть видео отдельной страницей.",
                verbose_name="Видеоурок (ссылка на YouTube)",
            ),
        ),
    ]
