# Generated by Django 6.1.1 on 2026-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0008_alter_topic_theory_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description_kk",
            field=models.TextField(blank=True, verbose_name="Сипаттамасы (қазақша)"),
        ),
        migrations.AddField(
            model_name="task",
            name="input_example_kk",
            field=models.TextField(blank=True, verbose_name="Кіріс мысалы (қазақша)"),
        ),
        migrations.AddField(
            model_name="task",
            name="output_example_kk",
            field=models.TextField(blank=True, verbose_name="Шығыс мысалы (қазақша)"),
        ),
        migrations.AddField(
            model_name="task",
            name="title_kk",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Атауы (қазақша)"
            ),
        ),
    ]
