# Generated by Django 6.1.1 on 2026-09-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0009_task_description_kk_task_input_example_kk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_class", models.CharField(max_length=10, verbose_name="Класс")),
                ("points", models.IntegerField(verbose_name="Баллы")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "given_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_bonuses",
                        to="contest.teacher",
                        verbose_name="Кто поставил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баллы классу",
                "verbose_name_plural": "Баллы классам",
                "ordering": ["-created_at"],
            },
        ),
    ]
