# Generated by Django 6.1.1 on 2026-09-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0010_classbonus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["level", "title"]},
        ),
    ]
