# Generated by Django 6.1.1 on 2026-09-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0011_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="autotest_checked_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Когда прошёл последний прогон автотестов",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="autotest_passed",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Автотесты: пройдено"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="autotest_results",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{'ok': bool, 'error': None|'timeout'|'memory'|str, 'expected': str, 'actual': str}, ...]",
                verbose_name="Автотесты: детали по каждому тесту",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="autotest_total",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Автотесты: всего"
            ),
        ),
    ]
