# Generated by Django 6.1.1 on 2026-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0011_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="ai_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Ставится при любой попытке (успешной или нет) — чтобы не повторять проверку на каждой загрузке страницы, если она уже не удалась.",
                null=True,
                verbose_name="Когда была последняя ПОПЫТКА ИИ-проверки",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_feedback",
            field=models.TextField(blank=True, verbose_name="Обратная связь от ИИ"),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_plagiarism_note",
            field=models.TextField(
                blank=True,
                verbose_name="Заметка ИИ о найденном похожем решении (GitHub/интернет)",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда прошла ИИ-проверка (успешно)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Оценка ИИ (подсказка, не финальная)",
            ),
        ),
    ]
