# Generated by Django 6.1.1 on 2026-09-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0012_submission_autotest_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_graded",
            field=models.BooleanField(
                default=False, verbose_name="Проверено хотя бы раз"
            ),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер попытки")),
                ("code", models.TextField(blank=True, verbose_name="Код")),
                ("submitted_at", models.DateTimeField(verbose_name="Отправлено")),
                (
                    "score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Оценка (0-10)"
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="Комментарий учителя"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Проверено"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="contest.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["-number"],
            },
        ),
    ]
