# Generated by Django 6.1.1 on 2026-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0014_backfill_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="auto_graded",
            field=models.BooleanField(
                default=False, verbose_name="Оценено автоматически"
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="tests_passed",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Тестов пройдено"
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="tests_total",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Тестов всего"
            ),
        ),
    ]
