# Generated by Django 6.1.1 on 2026-09-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0018_english_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="theory_filename",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя файла теории"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="theory_html",
            field=models.TextField(blank=True, verbose_name="Теория (HTML)"),
        ),
    ]
