# Generated by Django 6.1.1 on 2026-09-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0019_topic_theory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school_class",
            field=models.CharField(max_length=10, verbose_name="Класс (например, 7F)"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="classes",
            field=models.CharField(
                blank=True,
                help_text="Классы этого учителя через запятую, например: 7F, 10A (пробелы, регистр и русские буквы исправятся сами)",
                max_length=255,
                verbose_name="Классы",
            ),
        ),
    ]
