# Generated by Django 6.1.1 on 2026-09-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0021_normalize_school_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("SOR", "СОР"), ("SOCH", "СОЧ")],
                        default="SOR",
                        max_length=4,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("school_class", models.CharField(max_length=10, verbose_name="Класс")),
                ("start_at", models.DateTimeField(verbose_name="Начало")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Длительность (минут)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="contest.teacher",
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="exams", to="contest.task", verbose_name="Задачи"
                    ),
                ),
            ],
            options={
                "verbose_name": "СОР/СОЧ",
                "verbose_name_plural": "СОР/СОЧ",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Начал")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершил досрочно"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="contest.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="contest.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка СОР/СОЧ",
                "verbose_name_plural": "Попытки СОР/СОЧ",
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(blank=True, verbose_name="Последний код")),
                (
                    "best_code",
                    models.TextField(
                        blank=True, verbose_name="Код с лучшим результатом"
                    ),
                ),
                (
                    "best_score",
                    models.IntegerField(default=0, verbose_name="Лучший балл (0-10)"),
                ),
                ("tests_passed", models.IntegerField(default=0)),
                ("tests_total", models.IntegerField(default=0)),
                ("results", models.JSONField(blank=True, default=list)),
                ("submissions_count", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contest.task"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="contest.examattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на СОР/СОЧ",
                "verbose_name_plural": "Ответы на СОР/СОЧ",
                "unique_together": {("attempt", "task")},
            },
        ),
    ]
