# Generated by Django 6.1.1 on 2026-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0022_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="random_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Случайных задач каждому (0 — все)"
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="task_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Выпавшие задачи"
            ),
        ),
    ]
