# Generated by Django 6.1.1 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0023_exam_random_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="random_slots",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Условия случайных задач"
            ),
        ),
    ]
