"""
Django settings for pifagor_contest project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Все настройки ниже можно переопределить переменными окружения на сервере,
# при этом локальная разработка (без переменных окружения) продолжает
# работать как раньше — с DEBUG=True и базой SQLite.

# SECURITY WARNING: keep the secret key used in production secret!
# На сервере обязательно задайте свой DJANGO_SECRET_KEY через переменную окружения.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-16ns0#0b0k7%xykmhqe(^&3@j8=9sesr8egsmb5=ej!5(3x+7u',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# На сервере задайте DJANGO_ALLOWED_HOSTS, например: "1.2.3.4,pifagor.example.com"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Отдаёт статику прямо из Gunicorn — нужно для хостингов вроде Render,
    # где нет отдельного Nginx перед приложением. На Oracle-деплое с Nginx
    # не мешает: запросы к /static/ там перехватывает сам Nginx раньше.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pifagor_contest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contest.context_processors.content_lang',
            ],
        },
    },
]

WSGI_APPLICATION = 'pifagor_contest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# По умолчанию — SQLite (как раньше, для локальной разработки).
# На сервере задайте DJANGO_DB_ENGINE=postgres и остальные POSTGRES_* переменные,
# чтобы использовать PostgreSQL (нужен пакет psycopg2-binary из req.txt).

if os.environ.get('DJANGO_DB_ENGINE') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'pifagor'),
            'USER': os.environ.get('POSTGRES_USER', 'pifagor'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            # Некоторые бесплатные Postgres-хостинги (например, Neon) требуют SSL.
            'OPTIONS': {'sslmode': os.environ.get('POSTGRES_SSLMODE', 'prefer')},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Статика приложений (например, contest/static/) находится автоматически через
# AppDirectoriesFinder, отдельная папка static/ в корне проекта не используется.
# STATIC_ROOT — куда `collectstatic` соберёт все файлы для раздачи (Nginx на
# Oracle-сервере или WhiteNoise на хостингах без отдельного веб-сервера).
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'

# Автоматический выход по бездействию: сессия истекает через 10 минут без запросов.
# SESSION_SAVE_EVERY_REQUEST обновляет "время жизни" сессии на каждом запросе — то есть
# таймер сбрасывается, пока пользователь активен, и сессия протухает только если он
# действительно ничего не делал 10 минут подряд (актуально для общих школьных компьютеров).
SESSION_COOKIE_AGE = 600  # 10 минут
SESSION_SAVE_EVERY_REQUEST = True